

[firebase]
type = "service_account"
project_id = "react-app-eb896"
private_key_id = "789fe99a47314e3f36b76869f48e394b49cd8da1"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCJ58Rc3yRqNFYy
Oz07rF9j3Vxhd9gArKyyTOPQpM2nSJvAGhDVIHWXc25PwBh1AlSQI2lcLYaasOsN
e1lG0AfzD/mdY4K+WSjmiOlKTmPoX4fNp9vZKQhRZV3OdUX5zEwL++hkXCPNXe0R
VSFaU9Pmk9pEgVkfCT5/S9u5u9lDk8KAWBt4+kyUQP9I0iKawyPkvDK8BjeaXATZ
0w1l+lFYrvZqeANH1IFL//jmMqJhdyxMGImnHTwrxLgt/S2hiNokyTDUhvihPcRh
cZ7+XCt1zTm18/dH2b7HSU8cEaohw+pjV2LFzVQLjzDjXGQYjPK9kbNIMp8vsQE6
2y3wrqD1AgMBAAECggEAALfDJggUrxn/AgWqIJbWZQLPrEOTgyAfmlF200R90GSm
zuSSKB9Ra7Ghn37OS+O6jswlBYq7BJwCdTVtqLiSBCC+cvVAkMkHjOtv46SuBpwR
vd5UhX78ax/VttMO+VGoDDSojUBXG67/+iPvYOdhsfWWD5t9EhXWyRlr6AfUQo2m
hJKSRX4Bq+dRGAK4g3suUPEquRvIT7YJriYfZLPocH4xtmLBnBkRkNGyaQ6bVVaU
FWA8vtjKq/hLFnq00FLdSNjdKsXoiMd5BXK7nSc4Ml4icmk5uremPHBMKOM7uBV+
S/FoS4dKxFiF12Jd4vRzK2salvDRrMyVttK/6HANRwKBgQDBt8fbaTpe1wDdGPQ4
rRAY17Er7jVr5I/hWbfsOvuDE1XK+qnTQ4PlzgCJo0iv3YHhHA5R+RoQWTCzx65x
HI5R04GIkOWTqtqglxBy8z9Xz7G5cf0gACTPZeQ4iWXjUb9rUjDhSpgYx8S/1pNV
8PdjqwQ2kbxEghlfAnBsD3am5wKBgQC2PkHEqiHqm4JVISKo8U49pzFke1Jn9xm2
n/1gVhPjolexQH3fq7o32K7x9sU88wzupA8GJYWx5Xvmg1WbLmLNarQL1QWLoKdX
ydpmrunPece1fjYg2MB7vv9USU57yXCcPms6z1mpu7ko0gP/ts4BZZFVBjdUMNz6
/+yHcQmpwwKBgQCtd6LSCXKphqJRWo0nS2IEvPD8Q702tl9ZDnwyX8blYyUKNFhq
xCSSXlwA5GSshxBMwlDYetYqGZQRCRheVZHkGCAAaLAMAYzxDRU/ui7YtTWSuE5Q
n5BW4Ajzz6WbX5KnydvXgnKcjhbTKpSY+sStTXDiZLJQLqgFeiutuFMptQKBgGWS
t3dUV8j52Z9282lz7ObB++6EKX7Wo1c9Pqxl7XnvLq8VQdLbVNPxijhEENSSpr+P
YuxLF4P6Yp8szhbKuLjC4wzBMvEKnpp4X6jhjmFb/6oxaRvPkyClaIviu8KUmJYM
2BkUHmZSwbV1sFLi4Vi38lOQPmBHR7MB1yP6JaefAoGBALbKG7NcSY2F2M2NOMf7
XxtUfj6KvfxFPmPWXKRHjjXORiUmW2jPnOew3IiUH5U7yTgE56k/5JEgNoRDF/as
HK0Q+sGhuzoih6XWfrDGGnY0o+DEKlL7RBtS+Sll0eMk92acgDd4h7pTyIhYtjdk
xyu9ubd+j09S9EQP734eRYGR
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@react-app-eb896.iam.gserviceaccount.com"
client_id = "116993999232309082016"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40react-app-eb896.iam.gserviceaccount.com"
